# Generated by Django 5.0.4 on 2024-04-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cargos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carregamento",
            name="data_carregamento",
            field=models.DateTimeField(),
        ),
    ]
