# Generated by Django 5.0.4 on 2024-04-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0003_cargo_delete_carregamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="shipment_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="unloading_date",
            field=models.DateField(blank=True),
        ),
    ]
