# Generated by Django 5.0.4 on 2024-04-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0004_alter_cargo_shipment_date_alter_cargo_unloading_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="unloading_date",
            field=models.DateField(null=True),
        ),
    ]
