# Generated by Django 5.0.4 on 2024-04-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0006_alter_cargo_sale_or_disposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="destination_company",
            field=models.CharField(max_length=50, verbose_name="Empresa de Destino"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="driver",
            field=models.CharField(max_length=50, verbose_name="Nome do Motorista"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="number_nf",
            field=models.CharField(max_length=50, verbose_name="Número da Nota Fiscal"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="origin_company",
            field=models.CharField(max_length=50, verbose_name="Empresa de Origem"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="pallets_quantity",
            field=models.IntegerField(verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="sale_or_disposal",
            field=models.BooleanField(
                default=False, verbose_name="Os pallets foram vendidos ou descartados?"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="shipment_date",
            field=models.DateField(verbose_name="Data de Envio"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="unloading_date",
            field=models.DateField(null=True, verbose_name="Data de Recebimento"),
        ),
    ]
