# Generated by Django 5.0.4 on 2024-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0008_alter_cargo_unloading_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="number_nf",
            field=models.IntegerField(
                max_length=50, verbose_name="Número da Nota Fiscal"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="pallets_quantity",
            field=models.IntegerField(verbose_name="Quantidade de Pallets"),
        ),
    ]
