# Generated by Django 5.0.4 on 2024-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0010_alter_cargo_number_nf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="destination_company",
            field=models.CharField(max_length=50, verbose_name="EMPRESA DE DESTINO"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="driver",
            field=models.CharField(max_length=50, verbose_name="NOME DO MOTORISTA"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="number_nf",
            field=models.IntegerField(verbose_name="Nº DA NOTA FISCAL"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="origin_company",
            field=models.CharField(max_length=50, verbose_name="EMPRESA DE ORIGEM"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="pallets_quantity",
            field=models.IntegerField(verbose_name="QUANTIDADE DE PALLETS"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="sale_or_disposal",
            field=models.BooleanField(
                default=False, verbose_name="OS PALLETS FORAM VENDIDOS OU DESCARTADOS?"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="shipment_date",
            field=models.DateField(verbose_name="DATA DE ENVIO"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="unloading_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="DATA DE RECEBIMENTO"
            ),
        ),
    ]
