# Generated by Django 5.0.4 on 2024-04-12 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0011_alter_cargo_destination_company_alter_cargo_driver_and_more"),
        ("companys", "0008_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="destination_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_cargos",
                to="companys.company",
                verbose_name="EMPRESA DE DESTINO",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="driver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companys.driver",
                verbose_name="NOME DO MOTORISTA",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="origin_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_cargos",
                to="companys.company",
                verbose_name="EMPRESA DE ORIGEM",
            ),
        ),
    ]
