# Generated by Django 5.0.4 on 2024-04-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0012_alter_cargo_destination_company_alter_cargo_driver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="vehicle_plate",
            field=models.CharField(
                default="AAA1A11", max_length=7, verbose_name="PLACA DO VEICULO"
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="voucher",
            field=models.BooleanField(
                default=False, verbose_name="O CLIENTE FINAL GEROU VALE PALLET?"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="number_nf",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Nº DA NOTA FISCAL"
            ),
        ),
    ]
