# Generated by Django 5.0.4 on 2024-04-13 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0013_cargo_vehicle_plate_cargo_voucher_and_more"),
        ("companys", "0011_alter_driver_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="PalletVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pallets", models.IntegerField(verbose_name="QUANTIDADE")),
                ("issue_date", models.DateField(verbose_name="DATA DE EMISSÃO")),
                (
                    "receipt_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="DATA DE RECEBIMENTO"
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_vouchers",
                        to="companys.company",
                        verbose_name="EMISSORA DO VALE",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_vouchers",
                        to="companys.company",
                        verbose_name="RECEBEDORA DO VALE",
                    ),
                ),
            ],
        ),
    ]
