# Generated by Django 5.0.4 on 2024-04-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0014_palletvoucher"),
        ("companys", "0011_alter_driver_address"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PalletVoucher",
            new_name="Voucher",
        ),
    ]
