# Generated by Django 5.0.4 on 2024-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0015_rename_palletvoucher_voucher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="shipment_date",
            field=models.DateTimeField(verbose_name="DATA DE ENVIO"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="unloading_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="DATA DE RECEBIMENTO"
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="issue_date",
            field=models.DateTimeField(verbose_name="DATA DE EMISSÃO"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="receipt_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="DATA DE RECEBIMENTO"
            ),
        ),
    ]
