# Generated by Django 5.0.4 on 2024-04-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cargos",
            "0016_alter_cargo_shipment_date_alter_cargo_unloading_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="shipment_date",
            field=models.DateField(verbose_name="DATA DE ENVIO"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="unloading_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="DATA DE RECEBIMENTO"
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="issue_date",
            field=models.DateField(verbose_name="DATA DE EMISSÃO"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="receipt_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="DATA DE RECEBIMENTO"
            ),
        ),
    ]
