# Generated by Django 5.0.4 on 2024-04-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0018_voucher_cargo_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voucher",
            old_name="cargo_id",
            new_name="cargo",
        ),
    ]
