# Generated by Django 5.0.4 on 2024-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0019_rename_cargo_id_voucher_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="driver",
            field=models.CharField(
                default="MOTORISTA", max_length=20, verbose_name="NOME DO MOTORISTA"
            ),
        ),
    ]
