# Generated by Django 5.0.4 on 2024-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0020_alter_cargo_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="driver",
            field=models.CharField(max_length=20, verbose_name="NOME DO MOTORISTA"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="sale_or_disposal",
            field=models.BooleanField(
                verbose_name="OS PALLETS FORAM VENDIDOS OU DESCARTADOS?"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="vehicle_plate",
            field=models.CharField(max_length=7, verbose_name="PLACA DO VEICULO"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="voucher",
            field=models.BooleanField(
                verbose_name="O CLIENTE FINAL GEROU VALE PALLET?"
            ),
        ),
    ]
