# Generated by Django 5.0.4 on 2024-04-18 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0021_alter_cargo_driver_alter_cargo_sale_or_disposal_and_more"),
        ("companys", "0013_alter_company_name_alter_company_pallets_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="QUANTIDADE DE DÍVIDA")),
                (
                    "creditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts_due",
                        to="companys.company",
                        verbose_name="EMPRESA CREDORA",
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts_owed",
                        to="companys.company",
                        verbose_name="EMPRESA DEVEDORA",
                    ),
                ),
            ],
        ),
    ]
