# Generated by Django 5.0.4 on 2024-04-18 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0022_debt"),
        ("companys", "0014_company_is_reiter_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="associated_shipper",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_shipper",
                to="companys.company",
                verbose_name="EMBARCADOR ASSOCIADO",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cargo",
            name="responsible_branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsible_branch",
                to="companys.company",
                verbose_name="FILIAL RESPONSÁVEL",
            ),
            preserve_default=False,
        ),
    ]
