# Generated by Django 5.0.4 on 2024-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0023_cargo_associated_shipper_cargo_responsible_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="amount",
            field=models.IntegerField(verbose_name="VALOR DA DÍVIDA"),
        ),
    ]
