# Generated by Django 5.0.4 on 2024-05-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0024_alter_debt_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="appointment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="DATA PREVISTA DE RECEBIMENTO"
            ),
        ),
    ]
