# Generated by Django 5.0.4 on 2024-04-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carregamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_carregamento", models.DateTimeField(auto_now_add=True)),
                ("data_entrega", models.DateTimeField(blank=True)),
                ("quantidade_pallets", models.IntegerField()),
                ("empresa_origem", models.CharField(max_length=50)),
                ("empresa_destino", models.CharField(max_length=50)),
                ("numero_nota_fiscal", models.CharField(max_length=50)),
                ("motorista", models.CharField(max_length=50)),
                ("venda_ou_descarte", models.BooleanField(blank=True)),
            ],
        ),
    ]
