# Generated by Django 5.0.4 on 2024-04-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                ("pallet_balance", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FinalCustomerBranch",
            fields=[
                (
                    "company_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="companys.company",
                    ),
                ),
            ],
            bases=("companys.company",),
        ),
        migrations.CreateModel(
            name="ReiterBranch",
            fields=[
                (
                    "company_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="companys.company",
                    ),
                ),
            ],
            bases=("companys.company",),
        ),
        migrations.CreateModel(
            name="ShipperBranch",
            fields=[
                (
                    "company_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="companys.company",
                    ),
                ),
            ],
            bases=("companys.company",),
        ),
    ]
