# Generated by Django 5.0.4 on 2024-04-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalcustomerbranch",
            name="pallet_storage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reiterbranch",
            name="pallet_storage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipperbranch",
            name="pallet_storage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="pallet_balance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
