# Generated by Django 5.0.4 on 2024-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0002_finalcustomerbranch_pallet_storage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reiterbranch",
            name="company_ptr",
        ),
        migrations.RemoveField(
            model_name="shipperbranch",
            name="company_ptr",
        ),
        migrations.AddField(
            model_name="company",
            name="name",
            field=models.CharField(default="Empresa", max_length=15),
        ),
        migrations.DeleteModel(
            name="FinalCustomerBranch",
        ),
        migrations.DeleteModel(
            name="ReiterBranch",
        ),
        migrations.DeleteModel(
            name="ShipperBranch",
        ),
    ]
