# Generated by Django 5.0.4 on 2024-04-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0003_remove_reiterbranch_company_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="pallet_balance",
        ),
        migrations.AddField(
            model_name="company",
            name="pallets_balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="pallets_storage",
            field=models.IntegerField(default=0),
        ),
    ]
