# Generated by Django 5.0.4 on 2024-04-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0004_remove_company_pallet_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(default="Empresa", max_length=50),
        ),
    ]
