# Generated by Django 5.0.4 on 2024-04-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0005_alter_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="cnpj",
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(max_length=100, verbose_name="ENDEREÇO"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                default="Empresa", max_length=50, verbose_name="NOME"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="pallets_balance",
            field=models.IntegerField(default=0, verbose_name="SALDO DE PALLETS"),
        ),
        migrations.AlterField(
            model_name="company",
            name="pallets_storage",
            field=models.IntegerField(default=0, verbose_name="ESTOQUE DE PALLETS"),
        ),
    ]
