# Generated by Django 5.0.4 on 2024-04-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0006_remove_company_cnpj_alter_company_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="reiter_filial",
            field=models.BooleanField(default=False, verbose_name="FILIAL DA REITER?"),
        ),
    ]
