# Generated by Django 5.0.4 on 2024-04-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0008_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="address",
        ),
        migrations.RemoveField(
            model_name="company",
            name="reiter_filial",
        ),
    ]
