# Generated by Django 5.0.4 on 2024-04-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0009_remove_company_address_remove_company_reiter_filial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="address",
            field=models.CharField(
                default="Bairro/Cidade", max_length=100, verbose_name="ENDEREÇO"
            ),
        ),
    ]
