# Generated by Django 5.0.4 on 2024-04-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0010_driver_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="address",
            field=models.CharField(
                default="Bairro, Cidade - UF", max_length=100, verbose_name="ENDEREÇO"
            ),
        ),
    ]
