# Generated by Django 5.0.4 on 2024-04-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cargos", "0020_alter_cargo_driver"),
        ("companys", "0011_alter_driver_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Driver",
        ),
    ]
