# Generated by Django 5.0.4 on 2024-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0012_delete_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=50, verbose_name="NOME"),
        ),
        migrations.AlterField(
            model_name="company",
            name="pallets_balance",
            field=models.IntegerField(verbose_name="SALDO DE PALLETS"),
        ),
        migrations.AlterField(
            model_name="company",
            name="pallets_storage",
            field=models.IntegerField(verbose_name="ESTOQUE DE PALLETS"),
        ),
    ]
