# Generated by Django 5.0.4 on 2024-04-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0013_alter_company_name_alter_company_pallets_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_reiter_branch",
            field=models.BooleanField(default=1, verbose_name="É FILIAL DA REITER?"),
            preserve_default=False,
        ),
    ]
