# Generated by Django 5.0.4 on 2024-04-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companys", "0014_company_is_reiter_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, verbose_name="NOME"),
        ),
        migrations.AlterField(
            model_name="company",
            name="pallets_balance",
            field=models.IntegerField(default=0, verbose_name="SALDO DE PALLETS"),
        ),
        migrations.AlterField(
            model_name="company",
            name="pallets_storage",
            field=models.IntegerField(default=0, verbose_name="ESTOQUE DE PALLETS"),
        ),
    ]
